### ISSUE TITLE
Use check constraints?

### ISSUE THREAD

**Issue by Matt-Eva** [learn-co-curriculum/python-p4-flask-sqlalchemy-lab#1]
### Canvas Link

https://learning.flatironschool.com/courses/6182/assignments/208460?module_item_id=480475

### Concern

Was our intention to have students use a check constraint on our environment column for enclosures? We specify that the environment type should belong to one of three different types. If we want them to be familiar with constraints at this point, we might want to give a brief example of how to use them with flask-sqlalchemy (basically just prepend `CheckConstraint` with`db.`). The docs don't explain this in any detail, and I managed to figure it out through trial and error.

If we are going to talk about this later on, we may not want to tell students that the environment can only be one of three types, as this could be confusing or misleading to students.

**Comment by professor-ben** [comment]
Hey Matt,

The structure of Phase 4 right now follows the _old_ structure of Phase 4, wherein constraints and validations are addressed later on. This is on our radar to change (ideally moving into Phase 3), but will require some more significant refactoring later on.

For now, I've added a note that we are not truly enforcing this rule, but it's one to keep in mind as they design. I mentioned that we will cover constraints later and mentioned what they can do.

Thanks,
Ben

**Comment by Matt-Eva** [comment]
Thanks Ben! 

We do have material on check constraints in phase 3 at the moment, which I think is great -  we just haven't specified how to use them with `flask-sqlalchemy` at this point instead of vanilla sqlalchemy. Just for context!
