### ISSUE TITLE
Passes Pytest but not CodeGrade

### ISSUE THREAD

**Issue by jessicavaughn619** [learn-co-curriculum/python-p4-flask-sqlalchemy-lab#7]
### Canvas Link

https://learning.flatironschool.com/courses/6193/assignments/234443?module_item_id=549347

### Concern

After passing all of the Pytests in this lab, my code still fails the CodeGrade assessment. Attached code in additional context for review. I am not sure if it is an issue with CodeGrade or if I am missing something. Thank you for your time!

### Additional Context

Here is my code, which passes the Pytests but fails CodeGrade:

https://github.com/jessicavaughn619/python-p4-flask-sqlalchemy-lab

**Comment by professor-ben** [comment]
Hi Jessica,

Can you double check and make sure you're pushing your database alongside your code?

Thanks,
Ben

**Comment by jessicavaughn619** [comment]
Hi Ben,

Thank you for reaching out to me. I believe I am pushing up my database alongside my code, I made sure to push to git from the top level of my project. I tried to run CodeGrade again and still failed the test. Please let me know if you think of anything else you'd like me to try. I had the same issue with a few of the other labs after this one.

Jessica

**Comment by professor-ben** [comment]
Thanks for double checking! I'll have @pgill97 take a look at this from here on out- he's something of a CodeGrade expert.

-Ben

**Comment by linda-seiter** [comment]
codegrade script updated
